### ISSUE TITLE
Changes to URL?

### ISSUE THREAD

**Issue by gponimansky** [Voidustries/Poly_Project#1]
Current URL displays as /Poly_Project which seems off. 
URL will be lowercase for the poly_project perhaps an change to poly will be better?

**Comment by StoneMonarch** [comment]
I'll see about adding a subdomain to Poly to this website will be under:

https://poly.voidustrues.ca/

Change to the auto generated website will have to be made to work with the new URL format

**Comment by gponimansky** [comment]
_https://poly.voidustries.ca/_ * Sounds good. 

Planning to keep this issue open until the changes have been made.

**Comment by StoneMonarch** [comment]
Just set up cloudflare as a nameserver, URLs might be down for 1-2 hours while nameservers are changed. Possibly the new URL for poly will work once the changes has been made

**Comment by StoneMonarch** [comment]
New URL is https://www.voidustries.ca/Poly/

Website is auto generated from the docs folder in the master branch of Voidustries/Poly

Issue closed and use of this repo can be discontinued.
